import './globals.css'
import { Kumbh_Sans } from 'next/font/google'

const kumbh = Kumbh_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--kumbh',
  weight: ['400', '500', '700'],
})

export const metadata = {
  title: 'Ecommerce Product Page',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={kumbh.variable}>{children}</body>
    </html>
  )
}

export default RootLayout
